version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: orders
      - name: customers

  - name: stripe
    database: raw
    loaded_at_field: _batched_at
    freshness: # check the freshness of the source data
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
    tables:
      - name: payment
        description: first level of our payments staging environment

  - name: ticket_tailor
    description: "Event and ticket data from ticket tailor"
    database: raw
    tables:
      - name: events
        columns: 
          - name: id
            test:
              - not_null

      - name: orders
      - name: issued_tickets
